name: flatland-baselines
dependencies:
  - python==3.12.9
  - pip:
      - pytest
      # DEPENDENCY SWITCH:
      # TODO use versioned dependency instead of latest
      - git+https://github.com/flatland-association/flatland-rl.git@main
