name: flatland-baselines
dependencies:
  - python==3.12.9
  - pip:
      # DEPENDENCY SWITCH:
      # TODO use versioned dependency instead of latest
      - pytest
      - git+https://github.com/flatland-association/flatland-rl.git@inject-policy-obs-builder-through-env-vars
